x-volumes: &volumes
  - ./source/enumerific:/source/enumerific
  - ./source/enumerific:/usr/local/lib/python/site-packages/enumerific
  - ./tests:/tests

services:

  black:
    container_name: enumerific-black
    build:
      dockerfile: ./Dockerfile
      context: ./
    image: enumerific-black
    environment:
      - SERVICE=black
    volumes:
      *volumes

  tests:
    container_name: enumerific-tests
    build:
      dockerfile: ./Dockerfile
      context: ./
    image: enumerific-tests
    environment:
      - SERVICE=tests
    volumes:
      *volumes
