services:

  black:
    build:
      dockerfile: ./Dockerfile
      context: ./
    environment:
      - SERVICE=black
    command: black --check /source /tests
    volumes:
      - ./source/enumerific:/source/enumerific
      - ./source/enumerific:/usr/local/lib/python3.11/site-packages/enumerific
      - ./tests:/tests

  tests:
    build:
      dockerfile: ./Dockerfile
      context: ./
    environment:
      - SERVICE=tests
    command: pytest /tests
    volumes:
      - ./source/enumerific:/source/enumerific
      - ./source/enumerific:/usr/local/lib/python3.11/site-packages/enumerific
      - ./tests:/tests
